sudo: required
services: 
  - docker

before-install:
  - docker build -t carlosp7/docker-react -f Dockerfile.dev .

##Run test env
script:
  - docker run -e CI=true carlosp7/docker-react npm run test

##Deploy to AWS
deploy:
  provider: elasticbeanstalk
  region: "us-west-2" ##The ElasticBeansTalk Instance region
  app: "docker" ##The App name
  env: "Docker-env" ##The App env
  bucket_name: "elasticbeanstalk-us-west-2-306476627547" ##It is in S3
  bucket_path: "docker" ##Same that the app name
  on:
    branch: master ##anytime we push code to brand master, It is the time to deploy
  ##Generate de API keys in IAM Service in AWS
  ##Put the keys in travis CI env
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY